version: '3'

services:
  zookeeper:
    image: zookeeper:3.5.10
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

volumes:
  zookeeper_data:
  zookeeper_datalog: