version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /home/alertmanager/config.yml:/etc/alertmanager/config.yml
      - /home/alertmanager/template:/etc/alertmanager/template
    entrypoint:
      - /bin/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
