version: '3.1'
services:
  kibana:
    image: kibana:6.5.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://192.168.0.1:9200 #设置访问elasticsearch的地址
      I18N_LOCALE: zh-CN
    ports:
      - 5601:5601