version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.5.2
    container_name: elasticsearch
    environment:
      - node.name=192.168.1.1
      - cluster.name=test
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /etc/localtime:/etc/localtime
    ports:
      - 9200:9200
      - 9300:9300