version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5.10
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      maxBuffer: 20048576
      maxPacketSize: 20048576
      maxClientCnxns: 10000
    volumes:
      - /home/ops/zookeeper/logs/zoo1:/datalog/version-2
      - /home/ops/zookeeper/data/zoo1:/data/version-2
      - /home/ops/zookeeper/conf/zoo1/zoo.cfg:/conf/zoo.cfg
  zoo2:
    image: zookeeper:3.5.10
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/ops/zookeeper/logs/zoo2:/datalog/version-2
      - /home/ops/zookeeper/data/zoo2:/data/version-2
      - /home/ops/zookeeper/conf/zoo2/zoo.cfg:/conf/zoo.cfg
  zoo3:
    image: zookeeper:3.5.10
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - /home/ops/zookeeper/logs/zoo3:/datalog/version-2
      - /home/ops/zookeeper/data/zoo3:/data/version-2
      - /home/ops/zookeeper/conf/zoo3/zoo.cfg:/conf/zoo.cfg