version: "3"
services:
  nacos2:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos2
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=ip
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.1.1
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ./logs:/home/nacos/logs
    ports:
      # web port
      - 8848:8848
      # client grpc to server，服务请求
      - 9848:9848
      # server grpc to server，服务同步
      - 9849:9849
    restart: always